195 Show exif informations
firebirdberlin/nightdream pull request #204
Opened 2020-10-16 10:52 UTC by mastermichi

initial version

2020-10-26 21:44 UTC, firebirdberlin requested changes

2020-10-26 21:44 UTC, firebirdberlin commented on res/values-de/strings.xml
> +    <string name="seconds_15">15 Sekunden</string>#
```suggestion
    <string name="seconds_15">15 Sekunden</string>
```

2020-10-26 21:44 UTC, firebirdberlin commented on res/values-de/strings.xml
> +    <string name="slideshow_exif_summary">Zeigt EXIF - Informationen vom aktuellen Hintergrundbild</string>
Please sort by the strings by name witihin the file.

2020-10-26 21:44 UTC, firebirdberlin commented on res/values/strings.xml
> +    <string name="slideshow_exif_summary">Show EXIF - informations from current backgroundimage</string>
```suggestion
    <string name="slideshow_exif">Show EXIF information</string>
    <string name="slideshow_exif_summary">Show EXIF information for the current background image</string>
```

Please sort by name within the file.

2020-10-26 21:44 UTC, firebirdberlin commented on src/com/firebirdberlin/nightdream/Settings.java
> +        background_exif = settings.getBoolean("slideshowEXIF", false);
```suggestion
        background_exif = settings.getBoolean("backgroundEXIF", false);
```

2020-10-26 21:44 UTC, firebirdberlin commented on src/com/firebirdberlin/nightdream/ui/NightDreamUI.java
> +        exif = rootView.findViewById(R.id.exif);
exitTextView

2020-10-26 21:44 UTC, firebirdberlin commented on src/com/firebirdberlin/nightdream/ui/NightDreamUI.java
> +                        } catch (Exception e) {
no general exception handlers please

2020-10-26 21:44 UTC, firebirdberlin commented on src/com/firebirdberlin/nightdream/ui/NightDreamUI.java
> +                            exif.setText("Error reading exif information");
empty on error

2020-10-26 21:44 UTC, firebirdberlin commented on src/com/firebirdberlin/nightdream/ui/NightDreamUI.java
> +    private double convertGPS(String[] separated){
`convertArcMinToDegrees` ?

2020-10-26 21:44 UTC, firebirdberlin commented on src/com/firebirdberlin/nightdream/ui/NightDreamUI.java
> +        }
```suggestion
       String datetime = exif.getAttribute(ExifInterface.TAG_DATETIME);
        if (datetime != null) {
            String[] exifDateTime = datetime.split(" ");
            [...] 
        }
```
Ideally settings.dateformat and settings.getFullTimeFormat are used to format date and time.

2020-10-26 21:44 UTC, firebirdberlin commented on src/com/firebirdberlin/nightdream/ui/NightDreamUI.java
> +                    exifCountry = addresslist.get(0).getCountryName();
```suggestion
                    Address address =  addresslist.get(0);
                    exifCity = address.getLocality();
                    exifCountry = address.getCountryName();
```

2020-10-26 21:44 UTC, firebirdberlin commented on src/com/firebirdberlin/nightdream/ui/NightDreamUI.java
> +        if (exif.getAttribute(ExifInterface.TAG_GPS_LATITUDE) != null && exif.getAttribute(ExifInterface.TAG_GPS_LONGITUDE) != null) {
extract once and make use of it.

2020-10-27 10:27 UTC, mastermichi commented on res/values-de/strings.xml
> +    <string name="seconds_15">15 Sekunden</string>#
done

2020-10-27 10:32 UTC, mastermichi commented on src/com/firebirdberlin/nightdream/Settings.java
> +        background_exif = settings.getBoolean("slideshowEXIF", false);
done

2020-10-27 10:34 UTC, mastermichi commented on src/com/firebirdberlin/nightdream/ui/NightDreamUI.java
> +                            exif.setText("Error reading exif information");
done

2020-10-27 10:36 UTC, mastermichi commented on src/com/firebirdberlin/nightdream/ui/NightDreamUI.java
> +                    exifCountry = addresslist.get(0).getCountryName();
done

2020-10-27 10:42 UTC, mastermichi commented on src/com/firebirdberlin/nightdream/ui/NightDreamUI.java
> +        if (exif.getAttribute(ExifInterface.TAG_GPS_LATITUDE) != null && exif.getAttribute(ExifInterface.TAG_GPS_LONGITUDE) != null) {
done

2020-10-27 10:44 UTC, mastermichi commented on src/com/firebirdberlin/nightdream/ui/NightDreamUI.java
> +    private double convertGPS(String[] separated){
ok

2020-10-27 10:44 UTC, mastermichi commented on res/values-de/strings.xml
> +    <string name="slideshow_exif_summary">Zeigt EXIF - Informationen vom aktuellen Hintergrundbild</string>
done

2020-10-27 10:45 UTC, mastermichi commented on res/values/strings.xml
> +    <string name="slideshow_exif_summary">Show EXIF - informations from current backgroundimage</string>
done

2020-10-27 10:47 UTC, mastermichi commented on src/com/firebirdberlin/nightdream/ui/NightDreamUI.java
> +        exif = rootView.findViewById(R.id.exif);
done

2020-10-27 20:04 UTC, closed without merging